#!/bin/bash

function compile() {
  gcc -ansi -I./ -c $1.c -o $1.o
}

compile iteration
compile servicePoints
compile queue
compile postoffice
compile customer
compile parameters
compile simQ
compile statistics

# link them all together
gcc -I./ simQ.o statistics.o iteration.o servicePoints.o queue.o postoffice.o customer.o parameters.o -lgsl -o simQ

# todo: remove this run command before submission
./simQ testInput.txt 10000 fileOut.txt
