#!/bin/bash

function compile() {
  gcc -ansi -I./src -c src/$1.c -o src/$1.o
}

# compile each file
compile iteration
compile servicePoints
compile queue
compile postoffice
compile customer
compile parameters
compile simQ
compile statistics

# link them all together into an executable (simQ)
gcc -I./src src/simQ.o src/statistics.o src/iteration.o src/servicePoints.o src/queue.o src/postoffice.o src/customer.o src/parameters.o -lgsl -o simQ

# remove all object code after linking
rm src/*.o
