#!/bin/bash

# This should compile, link and run a single file C program

# first argument is name of the file (exluding the file extension)

echo "Compiling and running $1.c"
gcc -ansi -c $1.c -o $1.o

gcc $1.o -lgsl -lgslcblas -o $1.e

# dot e for executable

./$1.e

